services:
  - type: web
    name: agrosense
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
    preInstallCommand: |
      # Install Python and pip
      apt-get update && apt-get install -y python3 python3-pip
      # Install any Python dependencies your ML script needs
      pip3 install scikit-learn pandas numpy 