services:
  - type: web
    name: agrosense
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: PATH
        value: /usr/local/bin:/usr/bin:/bin
    preInstallCommand: |
      # Update package list and install Python
      apt-get update
      apt-get install -y python3 python3-pip
      # Create symlink to ensure python3 is available as 'python'
      ln -sf /usr/bin/python3 /usr/bin/python
      # Verify Python installation
      python3 --version
      # Install Python dependencies
      pip3 install scikit-learn pandas numpy
      # Verify pip installation
      pip3 --version 