services:
  - type: web
    name: agrosense
    env: node
    plan: free
    buildCommand: |
      # Install Python first
      apt-get update
      apt-get install -y python3-full python3-pip
      # Make python3 the default python
      update-alternatives --install /usr/bin/python python /usr/bin/python3 1
      # Install Python packages
      python3 -m pip install --no-cache-dir scikit-learn pandas numpy
      # Now build the Node.js app
      npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: PYTHONPATH
        value: /usr/bin/python3
      - key: PYTHONUNBUFFERED
        value: "1" 