services:
  - type: web
    name: agrosense
    env: node
    plan: free
    buildCommand: |
      # Install Python and create virtual environment
      apt-get update
      DEBIAN_FRONTEND=noninteractive apt-get install -y python3-full python3-pip python3-venv
      python3 -m venv /opt/venv
      chmod -R 777 /opt/venv
      # Activate virtual environment and install packages
      . /opt/venv/bin/activate
      pip3 install --no-cache-dir --break-system-packages scikit-learn pandas numpy
      # Now build the Node.js app
      npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: PYTHONPATH
        value: /opt/venv/bin/python
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PATH
        value: /opt/venv/bin:$PATH 